### ISSUE TITLE
Config fail to open - Laravel

### ISSUE THREAD

**Issue by kamil-michalak** [EvilFreelancer/easyrsa-php#3]
After You change location of config files i get 
"vendor/evilfreelancer/easyrsa-php/src/config/easy-rsa.php): failed to open stream: No such file or directory"

**Comment by EvilFreelancer** [comment]
Hello! Thanks for reporting this bug, i'll check

**Comment by EvilFreelancer** [comment]
Try 1.0.1 version, I've added small fix.

**Comment by kamil-michalak** [comment]
Yes. Now is ok. Thx
